### PR TITLE
[Backend] Db Server Stats

### LINKED ISSUE #10: Expose DB Server stats
Have an API end-point and an area on the UI (under "_System_") to show the following stats:

- Memory:
  - PhysicalMem: "4 GBytes",
  - FreeMem: "2.38 GBytes"
  - WorkingSet: "572.73 MBytes"
  - TotalMemoryMapped: "803.5 MBytes"
- CPU:
  - ProcessorAffinity: 3
  - UserProcessorTime: "00:46:21.9687500"
- DB stats:
  - CountOfIndexes: 4,
  - CountOfDocuments: 1080
  - SizeOnDisk: "259 MBytes"
- DB performance metrics:
  - RequestsPerSec (FiveMinuteRate): 0.2
  - IndexedPerSec (FiveMinuteRate): 0.2

[Link to the docs](https://ravendb.net/docs/article-page/latest/csharp/server/administration/statistics).

### PR DESCRIPTION
**Pull request by yj7o5**
partially closes #10

### CODE REVIEW

**Comment by yj7o5** [comment]
@AKlaus created as draft at-the-moment since I haven't fully tested it yet. You can go ahead and provide any remarks if you want.

**Comment by AKlaus** [comment]
Hi @yj7o5,
Thank you for submitting a PR. I'll write notes on the files and some here when they're applicable to multiple files.

1. Need automated tests to cover the new functionality. We aren't aiming 100% coverage but the main goal is to ensure that the feature works in principle and all fragile bits (usually, integration points) a covered by tests
2. All the new DTOs shouldn't be added to `Database.Common` project (it's a shared project with common classes between `Database` and `Domain`, see [the diagram here](https://github.com/ravendb/samples-yabt/tree/master/back-end)). The best way would be to add another service to `Domain` project (e.g. call it `ServerStatsService`). Put all the DTOs into a subfolder of the service folder.
3. The preferable way to communicate with the server by using the existing `IDocumentStore` rather than via HTTP. See [this link](https://ravendb.net/docs/article-page/latest/csharp/client-api/operations/maintenance/get-statistics).

**Review by AKlaus — CHANGES_REQUESTED** [review]

**Comment by yj7o5** [comment]
Thanks @AKlaus will go ahead and perform the changes.

**Comment by AKlaus** [comment]
Closing it, as it appears abandoned by the submitter (idle for more than a year)

**Pull request closed without merging**
